// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTakeout():Promise<string>;

export function ConfirmTakeout():Promise<string>;

export function GetIndexStatus():Promise<string>;

export function GetMedia(arg1:number,arg2:number,arg3:number):Promise<string>;

export function GetMonths():Promise<string>;

export function GetMovies(arg1:number):Promise<string>;

export function GetMoviesStatus():Promise<string>;

export function GetSettings():Promise<string>;

export function GetTakeoutStatus():Promise<string>;

export function IndexFolder(arg1:string):Promise<string>;

export function IndexMovies():Promise<string>;

export function PickFolder():Promise<string>;

export function SaveSettings(arg1:string):Promise<string>;

export function StartTakeout(arg1:string):Promise<string>;
