// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IndexFolder(arg1) {
  return window['go']['main']['App']['IndexFolder'](arg1);
}
