// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMedia(offset:number):Promise<string>;

export function GetIndexStatus():Promise<string>;

export function IndexFolder(arg1:string):Promise<string>;
