// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTakeout() {
  return window['go']['main']['App']['CancelTakeout']();
}

export function ConfirmTakeout() {
  return window['go']['main']['App']['ConfirmTakeout']();
}

export function GetBackupDrives() {
  return window['go']['main']['App']['GetBackupDrives']();
}

export function GetBackupStatus() {
  return window['go']['main']['App']['GetBackupStatus']();
}

export function GetIndexStatus() {
  return window['go']['main']['App']['GetIndexStatus']();
}

export function GetMedia(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMedia'](arg1, arg2, arg3);
}

export function GetMonths() {
  return window['go']['main']['App']['GetMonths']();
}

export function GetMovies(arg1) {
  return window['go']['main']['App']['GetMovies'](arg1);
}

export function GetMoviesStatus() {
  return window['go']['main']['App']['GetMoviesStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTakeoutStatus() {
  return window['go']['main']['App']['GetTakeoutStatus']();
}

export function IndexFolder(arg1) {
  return window['go']['main']['App']['IndexFolder'](arg1);
}

export function IndexMovies() {
  return window['go']['main']['App']['IndexMovies']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartBackup() {
  return window['go']['main']['App']['StartBackup']();
}

export function StartTakeout(arg1) {
  return window['go']['main']['App']['StartTakeout'](arg1);
}
